export const deptsNumber = {
  
    data:[{'name': '01 - Ain', 'number': '01'},
    {'name': '02 - Aisne', 'number': '02'},
    {'name': '03 - Allier', 'number': '03'},
    {'name': '04 - Alpes de Haute-Provence', 'number': '04'},
    {'name': '05 - Hautes-Alpes', 'number': '05'},
    {'name': '06 - Alpes-Maritimes', 'number': '06'},
    {'name': '07 - Ardèche', 'number': '07'},
    {'name': '08 - Ardennes', 'number': '08'},
    {'name': '09 - Ariège', 'number': '09'},
    {'name': '10 - Aube', 'number': '10'},
    {'name': '11 - Aude', 'number': '11'},
    {'name': '12 - Aveyron', 'number': '12'},
    {'name': '13 - Bouches du Rhône', 'number': '13'},
    {'name': '14 - Calvados', 'number': '14'},
    {'name': '15 - Cantal', 'number': '15'},
    {'name': '16 - Charente', 'number': '16'},
    {'name': '17 - Charente Maritime', 'number': '17'},
    {'name': '18 - Cher', 'number': '18'},
    {'name': '19 - Corrèze', 'number': '19'},
    {'name': '2A - Corse du Sud', 'number': '2A'},
    {'name': '2B - Haute-Corse', 'number': '2B'},
    {'name': "21 - Côte d'Or", 'number': '21'},
    {'name': "22 - Côtes d'Armor", 'number': '22'},
    {'name': '23 - Creuse', 'number': '23'},
    {'name': '24 - Dordogne', 'number': '24'},
    {'name': '25 - Doubs', 'number': '25'},
    {'name': '26 - Drôme', 'number': '26'},
    {'name': '27 - Eure', 'number': '27'},
    {'name': '28 - Eure-et-Loir', 'number': '28'},
    {'name': '29 - Finistère', 'number': '29'},
    {'name': '30 - Gard', 'number': '30'},
    {'name': '31 - Haute-Garonne', 'number': '31'},
    {'name': '32 - Gers', 'number': '32'},
    {'name': '33 - Gironde', 'number': '33'},
    {'name': '34 - Hérault', 'number': '34'},
    {'name': '35 - Ille-et-Vilaine', 'number': '35'},
    {'name': '36 - Indre', 'number': '36'},
    {'name': '37 - Indre-et-Loire', 'number': '37'},
    {'name': '38 - Isère', 'number': '38'},
    {'name': '39 - Jura', 'number': '39'},
    {'name': '40 - Landes', 'number': '40'},
    {'name': '41 - Loir-et-Cher', 'number': '41'},
    {'name': '42 - Loire', 'number': '42'},
    {'name': '43 - Haute-Loire', 'number': '43'},
    {'name': '44 - Loire-Atlantique', 'number': '44'},
    {'name': '45 - Loiret', 'number': '45'},
    {'name': '46 - Lot', 'number': '46'},
    {'name': '47 - Lot-et-Garonne', 'number': '47'},
    {'name': '48 - Lozère', 'number': '48'},
    {'name': '49 - Maine-et-Loire', 'number': '49'},
    {'name': '50 - Manche', 'number': '50'},
    {'name': '51 - Marne', 'number': '51'},
    {'name': '52 - Haute-Marne', 'number': '52'},
    {'name': '53 - Mayenne', 'number': '53'},
    {'name': '54 - Meurthe-et-Moselle', 'number': '54'},
    {'name': '55 - Meuse', 'number': '55'},
    {'name': '56 - Morbihan', 'number': '56'},
    {'name': '57 - Moselle', 'number': '57'},
    {'name': '58 - Nièvre', 'number': '58'},
    {'name': '59 - Nord', 'number': '59'},
    {'name': '60 - Oise', 'number': '60'},
    {'name': '61 - Orne', 'number': '61'},
    {'name': '62 - Pas-de-Calais', 'number': '62'},
    {'name': '63 - Puy-de-Dôme', 'number': '63'},
    {'name': '64 - Pyrénées-Atlantiques', 'number': '64'},
    {'name': '65 - Hautes-Pyrénées', 'number': '65'},
    {'name': '66 - Pyrénées-Orientales', 'number': '66'},
    {'name': '67 - Bas-Rhin', 'number': '67'},
    {'name': '68 - Haut-Rhin', 'number': '68'},
    {'name': '69 - Rhône', 'number': '69'},
    {'name': '69-L - Métropole de Lyon', 'number': '69-L'},
    {'name': '70 - Haute-Saône', 'number': '70'},
    {'name': '71 - Saône-et-Loire', 'number': '71'},
    {'name': '72 - Sarthe', 'number': '72'},
    {'name': '73 - Savoie', 'number': '73'},
    {'name': '74 - Haute-Savoie', 'number': '74'},
    {'name': '75 - Paris', 'number': '75'},
    {'name': '76 - Seine-Maritime', 'number': '76'},
    {'name': '77 - Seine-et-Marne', 'number': '77'},
    {'name': '78 - Yvelines', 'number': '78'},
    {'name': '79 - Deux-Sèvres', 'number': '79'},
    {'name': '80 - Somme', 'number': '80'},
    {'name': '81 - Tarn', 'number': '81'},
    {'name': '82 - Tarn-et-Garonne', 'number': '82'},
    {'name': '83 - Var', 'number': '83'},
    {'name': '84 - Vaucluse', 'number': '84'},
    {'name': '85 - Vendée', 'number': '85'},
    {'name': '86 - Vienne', 'number': '86'},
    {'name': '87 - Haute-Vienne', 'number': '87'},
    {'name': '88 - Vosges', 'number': '88'},
    {'name': '89 - Yonne', 'number': '89'},
    {'name': '90 - Territoire-de-Belfort', 'number': '90'},
    {'name': '91 - Essonne', 'number': '91'},
    {'name': '92 - Hauts-de-Seine', 'number': '92'},
    {'name': '93 - Seine-St-Denis', 'number': '93'},
    {'name': '94 - Val-de-Marne', 'number': '94'},
    {'name': "95 - Val-d'Oise", 'number': '95'},
    {'name': '971 - Guadeloupe', 'number': '971'},
    {'name': '972 - Martinique', 'number': '972'},
    {'name': '973 - Guyane', 'number': '973'},
    {'name': '974 - La Réunion', 'number': '974'},
    {'name': '976 - Mayotte', 'number': '976'}]
  
  
  };